//! Rasterises the WhatsApp Web icons in assets/icons/*.svg (24x24 viewBox, copied from the page)
//! into assets/icons.atlas as 8-bit coverage masks, and writes crates/ui/src/icon_ids.rs with the
//! matching `Icon` enum, so the tool and the ui can never disagree about the order.
//!
//! Layout: u8 count, then per icon `u8 size` and `u32 offset` (little endian), then the masks packed
//! like glyphs (`pack` in tools/bakefont, rows of `size` bytes; offsets from the start of the file).
//!
//! Run from the repository root: `cargo run --release -p bakeicons [preview.png]`.

#[path = "../../bakefont/src/pack.rs"]
mod pack;

use resvg::{tiny_skia, usvg};

/// (svg file, enum variant, pixel size). Sizes are the ones WhatsApp Web shows them at.
const ICONS: &[(&str, &str, u32)] = &[
    ("chats", "Chats", 24),
    ("calls", "Calls", 24),
    ("status", "Status", 24),
    ("channels", "Channels", 24),
    ("communities", "Communities", 24),
    ("media", "Media", 24),
    ("menu", "Menu", 24),
    ("new-chat", "NewChat", 24),
    ("search", "Search", 24),
    ("search", "SearchSmall", 20),
    ("check-double", "CheckDouble", 18),
    ("check", "Check", 18),
    ("chats-outline", "ChatsOutline", 24),
    ("call-filled", "CallsFilled", 24),
    ("dialpad", "Dialpad", 24),
    ("add-call", "AddCall", 24),
    ("videocam", "Videocam", 24),
    ("phone-incoming", "PhoneIncoming", 16),
    ("phone-outgoing", "PhoneOutgoing", 16),
    ("lock", "Lock", 16),
    ("videocam-filled", "VideocamBig", 64),
    ("video-call", "VideoCall", 24),
    ("link", "Link", 24),
    ("add", "Add", 14),
    ("add-circle", "AddCircle", 24),
    ("grid", "Grid", 20),
    ("verified", "Verified", 16),
    ("status-filled", "StatusFilled", 24),
    ("status-filled", "StatusBig", 64),
    ("channels-filled", "ChannelsFilled", 24),
    ("channels-filled", "ChannelsBig", 64),
    ("account-circle", "AccountCircle", 24),
    ("key", "Key", 24),
    ("lock", "LockBig", 24),
    ("notifications", "Notifications", 24),
    ("keyboard", "Keyboard", 24),
    ("help", "Help", 24),
    ("logout", "Logout", 24),
    ("description", "Description", 24),
    ("person-add", "PersonAdd", 24),
    ("meta", "Meta", 24),
    ("arrow-back", "Back", 24),
    ("group-add-filled", "GroupAddFilled", 29),
    ("person-add-filled", "PersonAddFilled", 29),
    ("communities-filled", "CommunitiesFilled", 29),
    ("person", "Person", 29),
    ("group-add", "MenuGroup", 18),
    ("archive", "MenuArchive", 18),
    ("grade", "MenuStar", 18),
    ("star", "StarSmall", 12),
    ("muted", "Muted", 16),
    ("check-box", "MenuSelect", 18),
    ("chats-outline", "MenuChats", 18),
    ("lock", "MenuLock", 18),
    ("logout", "MenuLogout", 18),
    ("backspace", "Backspace", 24),
    ("call-end", "CallEnd", 28),
];

fn render(svg: &str, size: u32) -> Vec<u8> {
    let tree = usvg::Tree::from_str(svg, &usvg::Options::default()).expect("valid svg");
    let mut pixmap = tiny_skia::Pixmap::new(size, size).expect("pixmap");
    let scale = size as f32 / tree.size().width();
    resvg::render(&tree, tiny_skia::Transform::from_scale(scale, scale), &mut pixmap.as_mut());
    pixmap.pixels().iter().map(|pixel| pixel.alpha()).collect()
}

fn main() {
    let masks: Vec<(u32, Vec<u8>)> = ICONS
        .iter()
        .map(|&(file, _, size)| {
            let path = format!("assets/icons/{file}.svg");
            (size, render(&std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("{path}: {e}")), size))
        })
        .collect();

    let packed: Vec<Vec<u8>> = masks
        .iter()
        .map(|(size, mask)| {
            let packed = pack::pack(*size as usize, *size as usize, mask);
            assert_eq!(&pack::unpack(*size as usize, *size as usize, &packed), mask, "icon does not round-trip");
            packed
        })
        .collect();
    let header = 1 + masks.len() * 5;
    let mut out = vec![masks.len() as u8];
    let mut offset = header;
    for ((size, _), packed) in masks.iter().zip(&packed) {
        out.push(*size as u8);
        out.extend((offset as u32).to_le_bytes());
        offset += packed.len();
    }
    for packed in &packed {
        out.extend(packed);
    }
    std::fs::write("assets/icons.atlas", &out).expect("write atlas");

    let variants: String = ICONS.iter().map(|&(_, name, _)| format!("    {name},\n")).collect();
    std::fs::write(
        "crates/ui/src/icon_ids.rs",
        format!("// Generated by tools/bakeicons from assets/icons; do not edit.\n\n#[derive(Clone, Copy)]\npub enum Icon {{\n{variants}}}\n"),
    )
    .expect("write icon_ids.rs");
    println!("assets/icons.atlas: {} bytes, {} icons", out.len(), masks.len());

    if let Some(path) = std::env::args().nth(1) {
        let cell = 40usize;
        let (w, h) = (masks.len() * cell, cell);
        let mut sheet = vec![[22u8, 23, 23]; w * h];
        for (n, (size, mask)) in masks.iter().enumerate() {
            let size = *size as usize;
            for (i, alpha) in mask.iter().enumerate() {
                let (x, y) = (n * cell + (cell - size) / 2 + i % size, (cell - size) / 2 + i / size);
                for c in 0..3 {
                    sheet[y * w + x][c] = ((250 * *alpha as u32 + 22 * (255 - *alpha as u32)) / 255) as u8;
                }
            }
        }
        let mut encoder = png::Encoder::new(std::fs::File::create(&path).unwrap(), w as u32, h as u32);
        encoder.set_color(png::ColorType::Rgb);
        encoder.set_depth(png::BitDepth::Eight);
        encoder.write_header().unwrap().write_image_data(&sheet.iter().flatten().copied().collect::<Vec<u8>>()).unwrap();
        println!("preview: {path}");
    }
}
